# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreatePost():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createPost(self):
    self.driver.get("http://localhost:3000/login")
    self.driver.set_window_size(1440, 804)
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(1) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(1) > input").send_keys("mudu")
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(2) > input").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".input:nth-child(2) > input").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".menu-item:nth-child(3)").click()
    self.driver.find_element(By.NAME, "image").click()
    self.driver.find_element(By.NAME, "image").send_keys("C:\\fakepath\\417513458_10224184293424465_7888426214461609758_n.jpg")
    self.driver.find_element(By.NAME, "caption").click()
    self.driver.find_element(By.NAME, "caption").send_keys("me")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
